// Catálogo de voces IA + arquetipos anime/manga/cine
export const AI_VOICES = [
  // --- VOCES MASCULINAS ---
  { name: "Héroe Joven", gender: "male", age_range: "teen", nationality: "Japonés", personality: "valiente, apasionado", archetype: "shonen hero", openai_voice: "echo", avatar_emoji: "⚡", tags: ["anime", "shonen", "protagonista"], description: "Voz enérgica de adolescente protagonista estilo Naruto o Luffy", sample_text: "¡No me rendiré jamás! ¡Ese es mi camino del ninja!" },
  { name: "Guerrero Veterano", gender: "male", age_range: "adult", nationality: "Japonés", personality: "serio, honorable", archetype: "samurai", openai_voice: "onyx", avatar_emoji: "⚔️", tags: ["anime", "samurai", "bushido"], description: "Voz grave y serena de guerrero con años de experiencia", sample_text: "El honor no se conquista con fuerza, sino con sabiduría." },
  { name: "Villano Carismático", gender: "male", age_range: "adult", nationality: "Europeo", personality: "manipulador, elegante", archetype: "villain", openai_voice: "fable", avatar_emoji: "🎭", tags: ["villain", "carismático", "oscuro"], description: "Voz suave y amenazante de antagonista inteligente", sample_text: "Creías que ganabas... qué ingenuo." },
  { name: "Maestro Sabio", gender: "male", age_range: "senior", nationality: "Oriental", personality: "tranquilo, enigmático", archetype: "sensei", openai_voice: "onyx", avatar_emoji: "🧙", tags: ["sensei", "sabio", "misterioso"], description: "Voz pausada y profunda de maestro con gran sabiduría", sample_text: "El camino más largo siempre empieza con un pequeño paso." },
  { name: "Pirata Aventurero", gender: "male", age_range: "young_adult", nationality: "Español", personality: "extrovertido, leal", archetype: "pirate", openai_voice: "fable", avatar_emoji: "🏴‍☠️", tags: ["pirata", "aventura", "camaradería"], description: "Voz alegre y atrevida estilo One Piece", sample_text: "¡Yo seré el rey de los piratas! ¡Lo prometo!" },
  { name: "Ninja Silencioso", gender: "male", age_range: "young_adult", nationality: "Japonés", personality: "reservado, letal", archetype: "ninja", openai_voice: "echo", avatar_emoji: "🥷", tags: ["ninja", "oscuro", "sigiloso"], description: "Voz fría y controlada de shinobi de élite", sample_text: "Las sombras son mi hogar. El silencio, mi arma." },
  { name: "Cómico Bromista", gender: "male", age_range: "teen", nationality: "Latinoamericano", personality: "gracioso, impulsivo", archetype: "comic relief", openai_voice: "alloy", avatar_emoji: "😄", tags: ["comedia", "alegre", "bromista"], description: "Voz aguda y divertida perfecta para personajes cómicos", sample_text: "¡Esto es un plan perfecto! Aunque... ¿alguien trajo el mapa?" },
  { name: "Caballero Medieval", gender: "male", age_range: "adult", nationality: "Europeo", personality: "noble, protector", archetype: "knight", openai_voice: "onyx", avatar_emoji: "🛡️", tags: ["fantasy", "caballero", "honor"], description: "Voz firme y noble de paladín medieval", sample_text: "¡Juro proteger este reino con mi vida y mi honor!" },
  { name: "Científico Excéntrico", gender: "male", age_range: "adult", nationality: "Alemán", personality: "genial, obsesivo", archetype: "scientist", openai_voice: "echo", avatar_emoji: "🔬", tags: ["ciencia", "genio", "loco"], description: "Voz intensa y acelerada de científico brillante", sample_text: "¡Eureka! ¡Mi invención cambiará el mundo! ¡Todo el mundo!" },
  { name: "Detective Noir", gender: "male", age_range: "adult", nationality: "Americano", personality: "cínico, perspicaz", archetype: "detective", openai_voice: "fable", avatar_emoji: "🕵️", tags: ["noir", "detective", "misterio"], description: "Voz ronca y reflexiva estilo detective de los 40s", sample_text: "En esta ciudad, todos mienten. Yo solo escucho mejor." },
  { name: "Demonio Antiguo", gender: "male", age_range: "senior", nationality: "Sobrenatural", personality: "arrogante, poderoso", archetype: "demon lord", openai_voice: "onyx", avatar_emoji: "👹", tags: ["demonio", "fantasy", "oscuro", "poderoso"], description: "Voz profunda y resonante de ser oscuro milenario", sample_text: "Humanos... qué criaturas tan patéticas y fascinantes a la vez." },
  { name: "Androide Frío", gender: "male", age_range: "young_adult", nationality: "Sin origen", personality: "lógico, desprovisto de emoción", archetype: "android", openai_voice: "alloy", avatar_emoji: "🤖", tags: ["sci-fi", "robot", "futuro"], description: "Voz plana y precisa de inteligencia artificial", sample_text: "Cálculo completado. Probabilidad de éxito: 12.7%." },

  // --- VOCES FEMENINAS ---
  { name: "Heroína Shojo", gender: "female", age_range: "teen", nationality: "Japonés", personality: "empática, determinada", archetype: "shojo heroine", openai_voice: "nova", avatar_emoji: "🌸", tags: ["anime", "shojo", "protagonista"], description: "Voz dulce pero valiente de protagonista shojo", sample_text: "¡El amor y la amistad son la fuerza más poderosa!" },
  { name: "Guerrera Élite", gender: "female", age_range: "young_adult", nationality: "Japonés", personality: "fría, perfeccionista", archetype: "kunoichi", openai_voice: "shimmer", avatar_emoji: "🗡️", tags: ["guerrera", "ninja", "élite"], description: "Voz serena y amenazante de kunoichi de alto rango", sample_text: "No existe el fracaso en mi vocabulario." },
  { name: "Princesa Mágica", gender: "female", age_range: "teen", nationality: "Fantástico", personality: "inocente, poderosa", archetype: "magical girl", openai_voice: "nova", avatar_emoji: "✨", tags: ["magia", "princess", "fantasy"], description: "Voz cristalina de chica mágica con gran poder latente", sample_text: "¡Poder del corazón, transfórmame! ¡En nombre del amor!" },
  { name: "Villana Seductora", gender: "female", age_range: "adult", nationality: "Europeo", personality: "manipuladora, elegante", archetype: "femme fatale", openai_voice: "shimmer", avatar_emoji: "🌹", tags: ["villana", "elegante", "peligrosa"], description: "Voz suave y envolvente de antagonista sofisticada", sample_text: "Los tontos siempre caen en mis redes. Es tan... predecible." },
  { name: "Sabia Anciana", gender: "female", age_range: "senior", nationality: "Oriental", personality: "misteriosa, protectora", archetype: "oracle", openai_voice: "alloy", avatar_emoji: "🔮", tags: ["sabia", "oráculo", "misterio"], description: "Voz calmada y profunda de guardiana del conocimiento", sample_text: "El destino no es fijo... pero tampoco es accidental." },
  { name: "Chica Tsundere", gender: "female", age_range: "teen", nationality: "Japonés", personality: "brusca pero sensible", archetype: "tsundere", openai_voice: "nova", avatar_emoji: "😤", tags: ["tsundere", "anime", "comedia"], description: "Voz enérgica con cambios bruscos de tono, clásica tsundere", sample_text: "¡N-no es que me importes o algo así! ¡Baka!" },
  { name: "Hada del Bosque", gender: "female", age_range: "child", nationality: "Fantástico", personality: "juguetona, libre", archetype: "fairy", openai_voice: "shimmer", avatar_emoji: "🧚", tags: ["hada", "fantasy", "niña", "mágica"], description: "Voz aguda y musical de ser mágico del bosque", sample_text: "¡Ven, te mostraré los secretos del bosque encantado!" },
  { name: "Científica Rebelde", gender: "female", age_range: "young_adult", personality: "inteligente, sarcástica", nationality: "Americano", archetype: "genius rebel", openai_voice: "alloy", avatar_emoji: "🧪", tags: ["ciencia", "rebelde", "inteligente"], description: "Voz segura y directa de genio que desafía el sistema", sample_text: "La ciencia no tiene moral. Las personas, sí. Esa es la diferencia." },
  { name: "Reportera Valiente", gender: "female", age_range: "adult", nationality: "Latinoamericano", personality: "decidida, curiosa", archetype: "journalist", openai_voice: "nova", avatar_emoji: "📰", tags: ["periodismo", "valentía", "investigación"], description: "Voz clara y enérgica de periodista de investigación", sample_text: "La verdad nunca se rinde, aunque el poder intente silenciarla." },
  { name: "Reina Oscura", gender: "female", age_range: "adult", nationality: "Fantástico", personality: "cruel, majestuosa", archetype: "dark queen", openai_voice: "shimmer", avatar_emoji: "👑", tags: ["reina", "oscura", "poderosa", "villana"], description: "Voz profunda y regia de soberana sin piedad", sample_text: "Arrodíllate. O serás el primero en caer." },

  // --- VOCES NEUTRAS / INFANTILES ---
  { name: "Niño Curioso", gender: "neutral", age_range: "child", nationality: "Español", personality: "inocente, aventurero", archetype: "child hero", openai_voice: "nova", avatar_emoji: "🌟", tags: ["niño", "inocente", "aventura"], description: "Voz tierna y curiosa de protagonista infantil", sample_text: "¿Y si hay dragones de verdad? ¡Yo quiero verlos!" },
  { name: "Espíritu del Viento", gender: "neutral", age_range: "young_adult", nationality: "Sobrenatural", personality: "libre, melancólico", archetype: "spirit", openai_voice: "alloy", avatar_emoji: "🌬️", tags: ["espíritu", "nature", "melancólico"], description: "Voz etérea y suave de entidad espiritual", sample_text: "Soy el susurro entre los árboles... el aliento de la tormenta." },
];

export const FAMOUS_VOICES = [
  // Arquetipos inspirados en PERSONAJES FICTICIOS DE ANIME (libres de uso por ser arquetipos)
  { name: "El Pirata del Sombrero de Paja", gender: "male", age_range: "teen", nationality: "Japonés", personality: "impulsivo, leal", archetype: "pirate captain", openai_voice: "fable", avatar_emoji: "🎩", tags: ["one piece", "pirata", "shonen"], description: "Arquetipo del protagonista despreocupado y temerario que quiere ser el mejor", sample_text: "¡Yo seré el rey de los piratas!" },
  { name: "El Ninja de la Hoja", gender: "male", age_range: "teen", nationality: "Japonés", personality: "determinado, ruidoso", archetype: "ninja protagonist", openai_voice: "echo", avatar_emoji: "🍃", tags: ["naruto", "ninja", "shonen"], description: "Arquetipo del ninja rechazado que busca reconocimiento con ganas incansables", sample_text: "¡Dattebayo! ¡Algún día seré Hokage!" },
  { name: "El Cazador de Demonios", gender: "male", age_range: "teen", nationality: "Japonés", personality: "amable, devastado por la tragedia", archetype: "demon slayer", openai_voice: "echo", avatar_emoji: "🌊", tags: ["demon slayer", "samurai", "anime"], description: "Arquetipo del cazador de demonios con corazón bondadoso que lucha por su familia", sample_text: "Protegeré a todos. Aunque me cueste la vida." },
  { name: "El Mago del Tiempo", gender: "male", age_range: "adult", nationality: "Fantástico", personality: "calculador, misterioso", archetype: "strategic mage", openai_voice: "onyx", avatar_emoji: "♟️", tags: ["strategy", "mago", "misterioso"], description: "Arquetipo del genio estratégico que siempre va diez pasos adelante", sample_text: "Todo está según mi plan. Exactamente según mi plan." },
  { name: "El Shinigami Rebelde", gender: "male", age_range: "teen", nationality: "Japonés", personality: "indiferente, protector oculto", archetype: "death god", openai_voice: "fable", avatar_emoji: "☠️", tags: ["bleach", "shinigami", "oscuro"], description: "Arquetipo del guerrero de la muerte con actitud fría pero lealtad profunda", sample_text: "No me interesa ser un héroe. Solo protejo lo que es mío." },
  { name: "La Bruja del Vacío", gender: "female", age_range: "teen", nationality: "Fantástico", personality: "solitaria, inmensamente poderosa", archetype: "void witch", openai_voice: "shimmer", avatar_emoji: "🌌", tags: ["fantasy", "magia", "oscura", "poderosa"], description: "Arquetipo de la maga con poderes destructivos que lucha por encontrar su lugar", sample_text: "Mi poder destruye todo lo que toco... por eso camino sola." },
  { name: "El Titan Gigante", gender: "male", age_range: "adult", nationality: "Europeo", personality: "torturado, determinado", archetype: "titan shifter", openai_voice: "onyx", avatar_emoji: "⚡", tags: ["attack on titan", "grimdark", "oscuro"], description: "Arquetipo del portador de un poder terrible con una misión imposible", sample_text: "Si mato a todos mis enemigos... ¿este mundo será libre?" },
  { name: "La Heroína Plus Ultra", gender: "female", age_range: "young_adult", nationality: "Japonés", personality: "apasionada, entregada", archetype: "pro hero", openai_voice: "nova", avatar_emoji: "💪", tags: ["my hero academia", "hero", "shonen"], description: "Arquetipo de la heroína profesional con sentido absoluto del deber", sample_text: "¡Plus Ultra! ¡Nunca me rindo mientras pueda luchar!" },
  // Arquetipos de cine/literatura clásica de dominio público
  { name: "El Detective de Baker Street", gender: "male", age_range: "adult", nationality: "Británico", personality: "brillante, excéntrico", archetype: "consulting detective", openai_voice: "fable", avatar_emoji: "🔍", tags: ["mystery", "detective", "victoriano"], description: "Arquetipo del detective genial de estilo victoriano con mente deductiva", sample_text: "Elemental. Todo está perfectamente claro si sabes observar." },
  { name: "El Conde de la Oscuridad", gender: "male", age_range: "senior", nationality: "Europeo del Este", personality: "aristocrático, aterrador", archetype: "vampire lord", openai_voice: "onyx", avatar_emoji: "🦇", tags: ["vampiro", "gótico", "horror", "clásico"], description: "Arquetipo del señor vampiro de la tradición gótica europea", sample_text: "La noche es eterna... igual que yo." },
  { name: "La Guerrera Amazona", gender: "female", age_range: "adult", nationality: "Greco-mítico", personality: "honorable, feroz", archetype: "amazon warrior", openai_voice: "shimmer", avatar_emoji: "🏹", tags: ["mitología", "guerrera", "honor"], description: "Arquetipo de la guerrera amazona de la mitología griega clásica", sample_text: "¡Por el Olimpo, que mi lanza nunca yerre el blanco!" },
  { name: "El Capitán de los Mares", gender: "male", age_range: "adult", nationality: "Americano", personality: "aventurero, libre", archetype: "sea captain", openai_voice: "echo", avatar_emoji: "⚓", tags: ["aventura", "mar", "libertad"], description: "Arquetipo del capitán de barco de la era de la aventura americana", sample_text: "El mar no tiene amos. Solo marineros que aprenden a respetarlo." },
];

export const OPENAI_VOICE_LABELS = {
  alloy: "Alloy – Neutral equilibrado",
  echo: "Echo – Masculino medio",
  fable: "Fable – Expresivo dramático",
  onyx: "Onyx – Masculino profundo",
  nova: "Nova – Femenino cálido",
  shimmer: "Shimmer – Femenino etéreo"
};